### ISSUE TITLE
can't init database in docker-compose

### ISSUE THREAD

**Issue by bifenglin** [casbin/casnode#445]
I have change the config as the doc [https://casnode.org/docs/docker](https://casnode.org/docs/docker) says. but when i run the command `docker-compose up`, it shows that the table doen't exist.
```
Starting casnode_db_1 ... done
Starting casnode_casnode_1 ... done
Attaching to casnode_db_1, casnode_casnode_1
db_1       | 2022-03-14 05:42:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
db_1       | 2022-03-14 05:42:23+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1       | 2022-03-14 05:42:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.
casnode_1  | wait-for-it: waiting 15 seconds for db:3306
db_1       | 2022-03-14T05:42:23.557933Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.25) starting as process 1
db_1       | 2022-03-14T05:42:23.564852Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1       | 2022-03-14T05:42:23.717104Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1       | 2022-03-14T05:42:23.778996Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_1       | 2022-03-14T05:42:23.808567Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1       | 2022-03-14T05:42:23.808682Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1       | 2022-03-14T05:42:23.811113Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1       | 2022-03-14T05:42:23.823341Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
casnode_1  | wait-for-it: db:3306 is available after 1 seconds
casnode_1  | 2022/03/14 05:42:24 载入sego词典 ./dictionary/dictionary.txt
casnode_1  | 2022/03/14 05:42:25 sego词典载入完毕
casnode_1  | panic: Error 1146: Table 'casdoor.user' doesn't exist
casnode_1  | 
casnode_1  | goroutine 1 [running]:
casnode_1  | github.com/casbin/casnode/casdoor.getOnlineUserCount()
casnode_1  |    /go/src/casnode/casdoor/user_adapter.go:81 +0x113
casnode_1  | github.com/casbin/casnode/casdoor.GetOnlineUserCount()
casnode_1  |    /go/src/casnode/casdoor/user.go:60 +0x25
casnode_1  | github.com/casbin/casnode/object.GetOnlineUserCount(...)
casnode_1  |    /go/src/casnode/object/member.go:130
casnode_1  | github.com/casbin/casnode/object.UpdateOnlineMemberNum()
casnode_1  |    /go/src/casnode/object/basic.go:231 +0x19
casnode_1  | github.com/casbin/casnode/object.InitForumBasicInfo()
casnode_1  |    /go/src/casnode/object/basic.go:39 +0x2a
casnode_1  | main.main()
casnode_1  |    /go/src/casnode/main.go:34 +0x6a
casnode_casnode_1 exited with code 2
```
the log show above.

**Comment by hsluoyz** [comment]
@Nekotoxin @ComradeProgrammer

**Comment by RyaoChengfeng** [comment]
Docker use `bridge` as default network driver, when running `docker-compose up`, container in the default bridge network `casdoor_default` cann't access to bridge network `casnode`. 

Containers should be placed on the same bridge network.

I can't deploy the service if I follow the documentation exactly

I think the doc https://casnode.org/docs/docker need to be corrected

**Comment by bifenglin** [comment]
> 

so how should i solve it?

**Comment by hsluoyz** [comment]
@Nekotoxin use the Casdoor docker solution
